#!/bin/bash

file=$(basename $1)
of=$(basename ${file^} .ms).pdf
echo $of

#file=$1
#file2=$(echo "${file^}")
#of=$(basename $file2 .ms).pdf
#echo $of

# nicht getestet
groff -k -ms $1 -T pdf > $HOME/Notizblock/$of
