#!/bin/bash

noteFilename="$HOME/Notizblock/.src/wochenplan-$(date +%V-%Y).ms"

if [ ! -f $noteFilename ]; then
	echo -e ".TL\n\
Wochenplanung\n\
.AU\n\
$(date '+%e. %b')\n\
.SH\n\
Agenda\n\
.IP \(bu"> $noteFilename
fi

nvim -c "norm Go"\
	-c "norm zz" $noteFilename
