#!/bin/bash
# _ __   __ _ 
#| '_ \ / _` |	Github
#| | | | (_| |	https://github.com/nichtgestalt/
#|_| |_|\__, |
#       |___/ 

declare -a options=(
"Cancel"
"Exit"
"Reboot"
"Shutdown"
)

choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i -l 5 -p 'Session')

case $choice in
	'Exit')
		pkill dwm ;;
	'Reboot')
		loginctl reboot ;;
	'Shutdown')
		loginctl poweroff ;;
esac
