#!/bin/bash

OLDIFS=$IFS
IFS=","

while read name addresse hnr plz ort mail mobil
do
	echo -e "\e[1;33m$name \
	-----------------------\e[0m\n\
	\t$addresse $hnr\n\
	\t$plz $ort\n\
	\tMail:  $mail\n\
	\tMobil: $mobil\n"
done < $1
IFS=$OLDIFS
