#!/bin/bash

noteFilename="$HOME/Notizblock/.src/tagesplanung-$(date +%Y-%m-%d).ms"

if [ ! -f $noteFilename ]; then
	echo -e ".TL\n\
Tagesplanung\n\
.AU\n\
$(date '+%e. %b')\n\
.SH\n\
Agenda\n\
.IP \(bu\n\
Morgenroutine
.IP \(bu\n\
Stimmung: /10\n\
.IP \(bu"> $noteFilename
fi

nvim -c "norm Go"\
	-c "norm zz" $noteFilename
